#!/bin/bash
#
# gamesman-classic
#

install=/home/gamers/gamesman_classic_install/GamesmanClassic
pid_file=$install/server.pid
log_file=$install/server.log
node=/usr/bin/node

start() {
	echo "Starting GamesmanClassic C to Web Server: "
	daemonize -c $install -u gamers -p $pid_file -o $log_file -e $log_file $node src/js/server.js
}

stop() {
	echo "Stopping GamesmanClassic C to Web Server."
	kill $(cat $pid_file)
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		stop
		start
		;;
	status)
		cat $log_file
		;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
