#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'python-daemon.devel',
 'build_date': '2009-04-03 12:54:59 +1100',
 'clean': None,
 'date': '2009-04-03 12:44:43 +1100',
 'revision_id': 'ben+python@benfinney.id.au-20090403014443-ppiyh6xivahcr0e8',
 'revno': 134}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
